---
- hosts: servers
  sudo: yes
  tasks:
    - name: Run server
      command: forever start File-upload-in-Node/server.js
    - name: Source bashrc
      shell: . ~/.bashrc
    - lineinfile: dest=.bashrc line="export TWILIO_SID='{{ lookup('env','TWILIO_SID') }}'"
    - lineinfile: dest=.bashrc line="export TWILIO_TOKEN='{{ lookup('env','TWILIO_TOKEN') }}'"
    - lineinfile: dest=.bashrc line="export MY_TWILIO_NO='{{ lookup('env','MY_TWILIO_NO') }}'"
    - lineinfile: dest=.bashrc line="export MY_PHONE_NO='{{ lookup('env','MY_PHONE_NO') }}'"    
