---
- hosts: servers
  sudo: yes
  tasks:
    - name: updates a server
      apt: update_cache=yes
    - name: Installs nodejs
      apt: pkg=nodejs state=installed update_cache=true
    - name: Installs npm
      apt: pkg=npm state=installed update_cache=true      
    - name: Installs git
      apt: pkg=git state=installed update_cache=true
    - name: Create symlink
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
    -name: Intall forever globally
      npm: pkg=forever global=yes

  handlers:
    - name: start nginx
      service: name=nginx state=started