---
- hosts: servers
  sudo: yes
  tasks:
    - name: Update server
      apt: update_cache=yes
    - name: Installs nodejs
      apt: pkg=nodejs state=installed update_cache=true
    - name: Installs npm
      apt: pkg=npm state=installed update_cache=true      
    - name: Installs git
      apt: pkg=git state=installed update_cache=true
    - name: Create symlink
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
    - name: Add the Redis PPA
      apt_repository: repo='ppa:rwky/redis' update_cache=yes
    - name: Install Redis from PPA
      apt: pkg=redis-server state=installed
    - name: Start Redis
      service: name=redis-server state=started
    - name: Intall forever globally
      npm: name=forever global=yes state=latest
    - name: Clone the application repo
      git: repo=https://github.com/DevOps-HeadBangers/Milestone3TargetApp.git dest=~/Milestone3TargetApp accept_hostkey=yes
    - name: Intall dependencies
      npm: path=~/Milestone3TargetApp
    - name: Export TWILIO_SID
      lineinfile: dest=.bashrc line="export TWILIO_SID='{{ lookup('env','TWILIO_SID') }}'"
    - name: Export TWILIO_TOKEN
      lineinfile: dest=.bashrc line="export TWILIO_TOKEN='{{ lookup('env','TWILIO_TOKEN') }}'"
    - name: Export MY_TWILIO_NO
      lineinfile: dest=.bashrc line="export MY_TWILIO_NO='{{ lookup('env','MY_TWILIO_NO') }}'"
    - name: Export MY_PHONE_NO
      lineinfile: dest=.bashrc line="export MY_PHONE_NO='{{ lookup('env','MY_PHONE_NO') }}'"    
    - name: Export M3_GMAIL
      lineinfile: dest=.bashrc line="export M3_GMAIL='{{ lookup('env','M3_GMAIL') }}'"    
    - name: Export M3_PASS
      lineinfile: dest=.bashrc line="export M3_PASS='{{ lookup('env','M3_PASS') }}'"          
    - name: Source bashrc
      shell: . ~/.bashrc
    - name: Run server
      command: forever start Milestone3TargetApp/server.js 104.131.193.51
      environment:
        TWILIO_SID: "{{ lookup('env','TWILIO_SID') }}"
        TWILIO_TOKEN: "{{ lookup('env','TWILIO_TOKEN') }}"
        MY_TWILIO_NO: "{{ lookup('env','MY_TWILIO_NO') }}"
        MY_PHONE_NO: "{{ lookup('env','MY_PHONE_NO') }}"
        M3_GMAIL: "{{ lookup('env','M3_GMAIL') }}"
        M3_PASS: "{{ lookup('env','M3_PASS') }}"
